#current active profile
spring:
    profiles:
        active: dev
camel.springboot.shutDownTimeout: 2

---
#dev profile
spring:
    profiles: dev
    
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none 
toRoute1: file:data/output        

message: DEV Environtment

---
#stage profile
spring:
    profiles: stage
    
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none 
toRoute1: file:data/output

message: STAGE Environtment

---
#prod profile
spring:
    profiles: prod
    
startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none 
toRoute1: file:data/output

message: PROD Environtment